
#Get all users
GET http://localhost:3001/users HTTP/1.1
Content-Type: application/json


###
#Crete a user

POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
    "id": "saurav.mauhgfhgcrya123@gmail.com",
      "password": "Saurav@29",
      "uname": "Saurav",
      "events":[{"name":"saurav"}]
}

###
#Update a user

PUT http://localhost:3001/users/saurav.maurya@gmail.com HTTP/1.1
Content-Type: application/json

{
    "uname":"saurav",
    "password":"saurav@29",
      "events":[{"name":"saurav"}]

}

###
#Delete a user

DELETE http://localhost:3001/users/6 HTTP/1.1
Content-Type:application/json

###
PATCH http://localhost:3001/users/saurav.maurya@gmail.com HTTP/1.1
Content-Type: application/json

{
      "events":[{"name":"saurav"}]
}

###

#Get all events

GET http://localhost:3001/events HTTP/1.1
Content-Type: application/json


###
#Crete an event

POST http://localhost:3001/events HTTP/1.1
Content-Type: application/json

{
    "name":"holi",
    "date":"29/08/2023",
    "type":"premium"
}

###
#Update an event

PUT http://localhost:3001/events/1 HTTP/1.1
Content-Type: application/json

{
    "name":"diwali",
    "date":"29/08/2023",
    "type":"premium"
}

###
#Delete an event

DELETE http://localhost:3001/events/8 HTTP/1.1
Content-Type:application/json